baseURL = 'blog.t0m.xyz/'
# baseURL = 'tomaz-suller.github.io/'
languageCode = 'en-gb'
title = 'tomaz-suller'
theme = 'PaperMod'
enableRobotsTXT = true
disableKinds = ['RSS']
copyright =  '''
This work by [Tomaz Maia Suller]({{< ref "/" >}}) is licensed under
[
    CC BY 4.0
    {{< inTextImg height=22px, url=https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1 >}}
    {{< inTextImg height=22px, url=https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1 >}}
](https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1)
'''

[services.googleAnalytics]
ID = 'G-DYJT4RW2E9'
[privacy.GoogleAnalytics]
RespectDoNotTrack = true

# Mathematics settings
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]']]
inline = [['\(', '\)']]

[markup.highlight]
noClasses = false

[params]
ShowShareButtons = true
ShareButtons = ['linkedin', 'reddit', 'whatsapp', 'telegram']
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "Hi, I'm Tomaz"
subtitle = 'a computer nerd trying to make the world a better place with AI'
imageUrl = 'profile.jpg'
imageHeight = 200
imageWidth = 200
[[params.socialIcons]]
name = 'github'
url = 'https://github.com/tomaz-suller'
[[params.socialIcons]]
name = 'linkedin'
url = 'https://linkedin.com/in/tomaz-suller'
[[params.socialIcons]]
name = 'cv'
url = 'cv.pdf'
[[params.profileMode.buttons]]
name = 'More about me'
url = 'about/'

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'
weight = 10

[[menu.main]]
identifier = 'research'
name = 'Research'
url = '/research/'
weight = 20

[[menu.main]]
identifier = 'projects'
name = 'Projects'
url = '/projects/'
weight = 30

[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 90
